class VectorStore:
    def add_text(self, text: str, source: str) -> str: ...  # -> id
    def search(self, query: str, top_n: int = 3) -> list[dict]: ...
    def get_by_id(self, id: str) -> dict: ...
